//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Samplee2.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_tbl
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string Designation { get; set; }
        public Nullable<double> Salary { get; set; }
    }
}
